# Generated by Django 6.0.5 on 2026-07-24 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekday', models.IntegerField(default=6, help_text='0=Monday .. 6=Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('hour', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(help_text='Next time this rule is due; advanced by the scheduler after each posting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rate', models.DecimalField(decimal_places=4, help_text='Nominal annual rate, e.g. 0.0500 = 5%/year.', max_digits=6)),
                ('schedule', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('weekday', models.IntegerField(default=6, help_text='Used when schedule=weekly. 0=Monday .. 6=Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('day_of_month', models.IntegerField(default=1, help_text='Used when schedule=monthly. Clamped to the last day of short months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('hour', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(help_text='Next time this rule is due; advanced by the scheduler after each posting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
