# Generated by Django 6.0.5 on 2026-07-24 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allowances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancerule',
            name='child',
            field=models.OneToOneField(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_rule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerule',
            name='funding_parent',
            field=models.ForeignKey(help_text='Parent whose account is debited each time this allowance is paid.', limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='funded_allowance_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestrule',
            name='child',
            field=models.OneToOneField(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, related_name='interest_rule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestrule',
            name='funding_parent',
            field=models.ForeignKey(help_text='Parent whose account is debited each time interest is paid.', limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='funded_interest_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
