# Generated by Django 6.0.5 on 2026-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='en', help_text='Preferred UI language -- purely a display preference for the frontend.', max_length=2),
        ),
    ]
