# Generated by Django 6.0.5 on 2026-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text="Google 'sub' claim -- set once this account signs in via Sign in with Google, and used to look it back up on every subsequent Google sign-in (see apps.users.services.GoogleAuthService).", max_length=255, null=True, unique=True),
        ),
    ]
