# Generated by Django 6.0.5 on 2026-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianship',
            name='is_creator',
            field=models.BooleanField(default=False, help_text="Whether this guardian is the parent who registered the child's account (set once, at creation -- see UserViewSet.perform_create). Only the creator may delete the child's account outright; every other guardian can only remove themselves from the guardianship (see apps.users.views.CanDeleteAccount)."),
        ),
    ]
