# Generated by Django 6.0.5 on 2026-07-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reverses',
            field=models.OneToOneField(blank=True, help_text='Set on a reversal transaction; points at the original transaction it cancels out. Once a transaction has a reversal, `objects.visible()` excludes both from listings/aggregates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversal', to='transactions.transaction'),
        ),
    ]
